WebApp/Areas/cms/Controllers/OkulFiyatlariController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebApp.Core;
using WebApp.Models;
using WebApp.Models.Repositories;

namespace WebApp.Areas.cms.Controllers
{
    public class OkulFiyatlariController : Controller
    {
        //
        // GET: /cms/OkulUcretleri/

        #region Degiskenler
        private IOkulRepository okulRepository = null;
        private IKursKategoriRepository kursKategoriRepository = null;
        private IKursTipiRepository kursTipiRepository = null;
        private IKursTipiFiyatlandirmalariRepository kursTipiFiyatlandirmalariRepository = null;
        private IKursTipiPromosyonTanimlariRepository kursTipiPromosyonTanimlariRepository = null;
        private IKursTipiEkUcretleriRepository kursTipiEkUcretleriRepository = null;
        private IMerkezRepository merkezRepository = null;
        private IKursTipiKargoHariclerRepository kursTipiKargoHariclerRepository = null;
        private GenericRepository<DilOkulu_Okullar> genericOkul = null;
        private GenericRepository<DilOkulu_KursTipleri> genericKursTipleri = null;
        private GenericRepository<DilOkulu_KursTipiFiyatlandirmalari> genericKursTipiFiyatlandirmalari = null;
        private GenericRepository<DilOkulu_KursTipiPromosyonTanimlari> genericKursTipiPromosyonTanimlari = null;
        private GenericRepository<DilOkulu_KursTipiEkUcretleri> genericKursTipiEkUcretleri = null;
        private GenericRepository<DilOkulu_KursTipiKargoHaricler> genericKursTipiKargoHaricler = null;
        private DilOkulu_Okullar okul = null;
        private List<DilOkulu_Okullar> okullar = null;
        #endregion

        #region KursTipleri
        public ActionResult KursTipi(int okulId = 0)
        {
            var okulDilId = OkulDilId(okulId);
            if (okulDilId > 0)
            {
                kursKategoriRepository = new KursKategoriRepository();
                var kursKategorileri = kursKategoriRepository.Liste()
                    .Where(kk => kk.DilId == okulDilId && kk.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kk => kk.Baslik).ToList();

                ViewBag.KursKategorileri = kursKategorileri;
            }

            ViewBag.OkulId = okulId.ToString();

            kursTipiRepository = new KursTipiRepository();
            var kursTipleri = kursTipiRepository.Liste().Where(kt => kt.OkulId == okulId && kt.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kt => kt.Baslik).ToList();

            return View(kursTipleri);
        }


        public ActionResult KursTipiEdit(int id = 0, int okulId = 0)
        {
            #region Kurs Kategorileri
            var okulDilId = OkulDilId(okulId);
            if (okulDilId > 0)
            {
                kursKategoriRepository = new KursKategoriRepository();
                var kursKategorileri = kursKategoriRepository.Liste()
                    .Where(kk => kk.DilId == okulDilId && kk.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kk => kk.Baslik).ToList();

                ViewBag.KursKategorileri = kursKategorileri;
            }
            #endregion

            ViewBag.OkulId = okulId.ToString();

            kursTipiRepository = new KursTipiRepository();
            var kursTipi = kursTipiRepository.Detay(id, new int[] { (byte)GeneralVariables.Durum.Aktif });

            return View(kursTipi);
        }

        [HttpPost]
        public ActionResult KursTipiEdit(FormCollection fColl, int id = 0, int okulId = 0)
        {
            #region Kurs Kategorileri
            var okulDilId = OkulDilId(okulId);
            if (okulDilId > 0)
            {
                kursKategoriRepository = new KursKategoriRepository();
                var kursKategorileri = kursKategoriRepository.Liste()
                    .Where(kk => kk.DilId == okulDilId && kk.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kk => kk.Baslik).ToList();

                ViewBag.KursKategorileri = kursKategorileri;
            }
            #endregion

            #region Variables
            var kursKategoriId = Convert.ToInt32("0" + fColl["kursKategorisi"]);
            var baslik = fColl["baslik"];
            var aciklama = HttpUtility.UrlDecode(fColl["kursTipiAciklama"]);
            var kursTipiTarih = fColl["kursTipiTarih"];
            var ozelTarihListesi = Request["ozelTarihListesi"].TrimEnd('|');
            bool basTarihiHerPazartesi = false;
            bool basTarihiOzel = false;
            #endregion

            ViewBag.OkulId = okulId.ToString();

            kursTipiRepository = new KursTipiRepository();
            var kursTipi = kursTipiRepository.Detay(id, new int[] { (byte)GeneralVariables.Durum.Aktif });
            if (kursTipi != null)
            {
                kursTipi.KursKategoriId = kursKategoriId;
                kursTipi.Baslik = baslik;
                kursTipi.Aciklama = aciklama;
                if (!string.IsNullOrEmpty(kursTipiTarih))
                {
                    if (kursTipiTarih == "ozel")
                    {
                        basTarihiOzel = true;
                        if (!string.IsNullOrEmpty(ozelTarihListesi))
                        {
                            kursTipi.BasTarihiHerPazartesi = false;
                            kursTipi.BasTarihiOzel = true;
                            kursTipi.OzelTarihListesi = ozelTarihListesi;
                        }

                    }
                    else
                    {
                        basTarihiHerPazartesi = true;
                        kursTipi.BasTarihiHerPazartesi = true;
                        kursTipi.BasTarihiOzel = false;
                        kursTipi.OzelTarihListesi = string.Empty;
                    }
                }

                genericKursTipleri = new GenericRepository<DilOkulu_KursTipleri>(kursTipiRepository.DBContext);
                var retVal = genericKursTipleri.Update(kursTipi);
                if (retVal != null)
                {
                    ViewBag.Status = "ok";
                }
                else
                {
                    ViewBag.Status = "error";
                }

            }
            return View(kursTipi);
        }

        /// <summary>
        /// Ajax Insert
        /// </summary>
        /// <returns></returns>
        public JsonResult KursTipiEkle()
        {
            #region Variables
            string status = "error";
            string message = "";
            var okulId = Convert.ToInt32("0" + Request["okulId"]);
            var baslik = Request["baslik"];
            var kursKategoriId = Convert.ToInt32("0" + Request["kursKategoriId"]);
            var basTarihiStatus = Request["basTarihiStatus"];
            var ozelTarihListesi = Request["ozelTarihListesi"].TrimEnd('|');
            var aciklama = HttpUtility.UrlDecode(Request["aciklama"]);

            bool basTarihiHerPazartesi = false;
            bool basTarihiOzel = false;

            if (basTarihiStatus == "ozel")
            {
                basTarihiOzel = true;
            }
            else
            {
                basTarihiHerPazartesi = true;
            }
            #endregion

            if (okulId > 0 && !string.IsNullOrEmpty(baslik) && kursKategoriId > 0)
            {
                kursTipiRepository = new KursTipiRepository();
                DilOkulu_KursTipleri yeniTip = new DilOkulu_KursTipleri()
                {
                    OkulId = okulId,
                    Baslik = baslik,
                    KursKategoriId = kursKategoriId,
                    Aciklama = aciklama,
                    KayitTarihi = DateTime.Now,
                    BasTarihiHerPazartesi = basTarihiHerPazartesi,
                    BasTarihiOzel = basTarihiOzel,
                    OzelTarihListesi = ozelTarihListesi,
                    Durumu = (byte)GeneralVariables.Durum.Aktif
                };

                genericKursTipleri = new GenericRepository<DilOkulu_KursTipleri>();
                var retVal = genericKursTipleri.Insert(yeniTip);
                if (retVal != null)
                {
                    status = "ok";
                }
                else
                {
                    message = "Kayıt işlemi sırasında problem ile karşılaşıldı!";
                }
            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Ajax Delete
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult KursTipiSil(int id = 0)
        {
            string status = "error";
            string message = "Hata:Silme işlemi yapılamadı!";

            if (id > 0)
            {
                kursTipiRepository = new KursTipiRepository();
                var kursTipi = kursTipiRepository.Liste().Where(kt => kt.Id == id).FirstOrDefault(); ;
                //&& kt.Durumu != (byte)GeneralVariables.Durum.Silindi
                if (kursTipi != null)
                {
                    genericKursTipleri = new GenericRepository<DilOkulu_KursTipleri>(kursTipiRepository.DBContext);
                    var retVal = genericKursTipleri.Delete(kursTipi);
                    if (retVal > 0)
                    {
                        status = "ok";
                        message = "Kayıt silindi!";
                    }
                    else
                    {
                        message = "Hata:Silme işlemi yapılamadı!";
                    }

                }

            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Fiyat Tanimlari
        public ActionResult FiyatTanimlari(int okulId = 0, int kursTipiId = 0)
        {

WebApp/Areas/cms/Views/OkulFiyatlari/FiyatTanimlari.cshtml
@{
    ViewBag.Title = "Fiyat Tanımları";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}

@section HeaderWithContentPage{
    <link href="@Url.Content("~/Areas/cms/Assets/css/smoothness/jquery-ui-1.11.4.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-ui-1.11.4.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/datepicker-tr.js")"></script>
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/fiyat_girisleri.js")"></script>

    <!-- Add mousewheel plugin (this is optional) -->
    <script src="@Url.Content("~/Areas/cms/Assets/fancybox/lib/jquery.mousewheel-3.0.6.pack.js")"></script>
    <!-- Add fancyBox -->
    <link rel="stylesheet" href="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.css?v=2.1.5")" type="text/css" media="screen" />
    <script type="text/javascript" src="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.pack.js?v=2.1.5")"></script>
}


@section SectionBeforeWrapper{
    @Html.Partial("_Modals")
}


<div id="divStatusBox" style="">
    <span id="spanMessageText"></span>
</div>
<table cellpadding="0" cellspacing="0" style="width: 100%;">
    <tr>
        <td class="MasterRow3_Column1">
            @Html.Partial("_OkullarMunu")
        </td>

        <td class="MasterRow3_Column2">
            @Html.Action("_OkulOzetBilgileri")
            @Html.Partial("_FiyatMenu")
            @Html.Partial("_FiyatTanimiEkle")
        </td>
    </tr>
</table>

<script type="text/javascript">
    $(function () {
        fiyatTanimi.init();
    })

</script>

WebApp/Areas/cms/Views/OkulFiyatlari/KonaklamaTanimlari.cshtml
@{
    ViewBag.Title = "Konaklama Tanımları";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}

@section SectionBeforeWrapper{
    @Html.Partial("_Modals")
}


<div id="divStatusBox" style="">
    <span id="spanMessageText"></span>
</div>
<table cellpadding="0" cellspacing="0" style="width: 100%;">
    <tr>
        <td class="MasterRow3_Column1">
            @Html.Partial("_OkullarMunu")
        </td>

        <td class="MasterRow3_Column2">
            @Html.Action("_OkulOzetBilgileri")
            @Html.Partial("_FiyatMenu")
            @*@Html.Partial("_KursTipiEkle")*@
        </td>
    </tr>
</table>

<script type="text/javascript">
    $(function () {

        //kursTipi.init();
        //kursTipi.tarihGoster('kursTipiOzelTarihGiris');

    })

</script>

WebApp/Areas/cms/Views/OkulFiyatlari/KursTipi.cshtml
@model List<WebApp.Models.DilOkulu_KursTipleri>
@{
    ViewBag.Title = "Kurs Tipi";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}

@section HeaderWithContentPage{
    <link href="@Url.Content("~/Areas/cms/Assets/css/smoothness/jquery-ui-1.11.4.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-ui-1.11.4.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/datepicker-tr.js")"></script>
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/fiyat_girisleri.js")"></script>

    <!-- Add mousewheel plugin (this is optional) -->
    <script src="@Url.Content("~/Areas/cms/Assets/fancybox/lib/jquery.mousewheel-3.0.6.pack.js")"></script>
    <!-- Add fancyBox -->
    <link rel="stylesheet" href="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.css?v=2.1.5")" type="text/css" media="screen" />
    <script type="text/javascript" src="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.pack.js?v=2.1.5")"></script>

}


@section SectionBeforeWrapper{
    @Html.Partial("_Modals")
}


<div id="divStatusBox" style="">
    <span id="spanMessageText"></span>
</div>
<table cellpadding="0" cellspacing="0" style="width: 100%;">
    <tr>
        <td class="MasterRow3_Column1">
            @Html.Partial("_OkullarMunu")
        </td>

        <td class="MasterRow3_Column2">
            @Html.Action("_OkulOzetBilgileri")
            @Html.Partial("_FiyatMenu")
            @Html.Partial("_KursTipiEkle")

            <!--Kurs Tipi Listesi-->

            <table id="hor-zebra" class="tblFiyatListesi" style="width: 780px; margin: 0px;">
                <caption>
                    <div style="font-size:15px;">
                        <strong>Kurs Tipi Listesi</strong>
                    </div>
                </caption>
                <thead>
                    <tr>
                        <th scope="col">Kategori</th>
                        <th>Kurs Tipi</th>
                        <th>Başlangıç Tarihleri</th>
                        <th>Açıklama</th>
                        <th colspan="2"><input id="Button1" type="button" onclick="kursTipi.tumKursTipiListesiniSil();" value="Tüm Fiyat Listesini Sil" /></th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model != null && Model != null && Model.Count > 0)
                    {
                        int Counter = 2;
                        foreach (var item in Model)
                        {
                            <tr class="fieldset" @(Counter % 2 == 0 ? "class=odd" : "")>
                                <td valign="top">@item.DilOkulu_KursKategorileri.Baslik <input id="hfId" value="@item.Id" type="hidden" /></td>
                                <td valign="top">
                                    @item.Baslik
                                </td>
                                <td valign="top">
                                    @if (Convert.ToBoolean(item.BasTarihiHerPazartesi))
                                    {
                                        @Html.Raw("Her Pazartesi")
                                    }
                                    else
                                    {
                                        foreach (var tarih in item.OzelTarihListesi.Split('|'))
                                        {
                                            @Html.Raw(tarih + "<br/>")
                                        }
                                    }
                                </td>
                                <td valign="top">
                                    <div style="max-width:200px;">
                                        @Html.Raw(item.Aciklama)
                                    </div>
                                </td>
                                <td valign="top">
                                    <div style="line-height:20px;">
                                        <a href="@Url.Action("FiyatTanimlari", "OkulFiyatlari", new { okulId = item.OkulId, kursTipiId = item.Id })">Fiyatlar</a><br />
                                        <a href="@Url.Action("PromosyonTanimlari", "OkulFiyatlari", new { okulId = item.OkulId, kursTipiId = item.Id })">Promosyonlar</a>
                                    </div>
                                </td>
                                <td>
                                    <a href="@Url.Action("KursTipiEdit", "OkulFiyatlari", new { id = item.Id, okulId = item.OkulId })">
                                        <img src="~/areas/CMS/assets/Images/edit_icon.png" style="width: 16px; height: 16px;" alt="Güncelle" />
                                    </a>
                                    <img src="/areas/CMS/assets/Images/delete_icon.png" onclick="kursTipi.kursTipiSil(@item.Id);" style="width: 16px; height: 16px;cursor:pointer;" alt="Sil" />

                                </td>
                            </tr>
                            Counter++;
                        }
                    }
                    else
                    {
                        @*<tr><td colspan="3"><strong>Kayıt bulunamadı...</strong></td></tr>*@
                    }
                </tbody>
            </table>
        </td>
    </tr>

</table>

<script type="text/javascript">
    $(function () {

        kursTipi.init();
        kursTipi.tarihGoster('kursTipiOzelTarihGiris');
    })

</script>

WebApp/Areas/cms/Views/OkulFiyatlari/KursTipiEdit.cshtml
@using WebApp.Models
@model DilOkulu_KursTipleri
@{
    ViewBag.Title = "Kurs Tipi Edit";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}
@{
    List<DilOkulu_KursKategorileri> kursKategorileri = null;
    if (ViewBag.KursKategorileri != null)
    {
        kursKategorileri = (List<DilOkulu_KursKategorileri>)ViewBag.KursKategorileri;
    }
}

@section HeaderWithContentPage{
    <link href="@Url.Content("~/Areas/cms/Assets/css/smoothness/jquery-ui-1.11.4.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-ui-1.11.4.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/datepicker-tr.js")"></script>
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/fiyat_girisleri.js")"></script>

    <!-- Add mousewheel plugin (this is optional) -->
    <script src="@Url.Content("~/Areas/cms/Assets/fancybox/lib/jquery.mousewheel-3.0.6.pack.js")"></script>
    <!-- Add fancyBox -->
    <link rel="stylesheet" href="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.css?v=2.1.5")" type="text/css" media="screen" />
    <script type="text/javascript" src="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.pack.js?v=2.1.5")"></script>

    <script type="text/javascript">
        $(function () {

            var ProcessStatus = '@Html.Raw(ViewBag.Status)';

            if (ProcessStatus == "ok") {
                GeneralObj.DilokuluMessageBox.init({ status: 'ok', message: 'Kayıt Güncellendi.' });
            } else if (ProcessStatus == "error") {
                GeneralObj.DilokuluMessageBox.init({ status: 'error', message: 'Hata: Kayıt Güncellenemedi!' });
            }

        })


    </script>
}


@section SectionBeforeWrapper{
    @Html.Partial("_Modals")
}


<div id="divStatusBox" style="">
    <span id="spanMessageText"></span>
</div>
<table cellpadding="0" cellspacing="0" style="width: 100%;">
    <tr>
        <td class="MasterRow3_Column1">
            @Html.Partial("_OkullarMunu")
        </td>

        <td class="MasterRow3_Column2">
            @Html.Action("_OkulOzetBilgileri")
            @Html.Partial("_FiyatMenu")
            <table cellpadding="0" cellspacing="0" class="OrtaMenu">
                <tr>
                    <td class="OrtaMenuRow">
                        @using (Html.BeginForm("KursTipiEdit", "OkulFiyatlari", new { id = Model.Id, okulId = Model.OkulId }, FormMethod.Post))
                        {
                            <table cellpadding="0" cellspacing="0" border="0" class="fiyatTable">
                                <tr>
                                    <td colspan="3">
                                        <img src="~/areas/CMS/assets/Images/edit_icon.png" style="width: 16px; height: 16px;" alt="Güncelle" />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="baslik">
                                        Kurs Kategorisi<span class="SpanZorunluAlan">*</span>
                                    </td>
                                    <td colspan="2">
                                        <select id="kursKategorisi" name="kursKategorisi" class="DropDownList">
                                            <option value="">Seçin...</option>
                                            @foreach (var item in kursKategorileri)
                                            {
                                                <option value="@item.Id" @(Model.KursKategoriId == item.Id ? "selected" : "")>@item.Baslik</option>
                                            }
                                        </select>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="baslik">Kurs Tipi<span class="SpanZorunluAlan">*</span></td>
                                    <td colspan="2">
                                        <input id="baslik" name="baslik" type="text" class="TextBox" style="width:300px;" value="@Model.Baslik" />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="baslik" style="vertical-align: top;">Başlangıç Tarihi</td>
                                    <td colspan="2" style="vertical-align: top;">
                                        @if (Convert.ToBoolean(Model.BasTarihiHerPazartesi))
                                        {
                                            <div class="TextBox">@Html.Raw("Her Pazartesi")</div>
                                        }
                                        else
                                        {
                                            <div class="TextBox">
                                                @foreach (var tarih in Model.OzelTarihListesi.Split('|'))
                                                {
                                                    @Html.Raw(tarih + "<br/>")
                                                }
                                            </div>
                                            <br />
                                        }
                                    </td>
                                </tr>

                                <tr>
                                    <td class="baslik">
                                        Açıklama
                                    </td>
                                    <td colspan="2">
                                        <textarea id="kursTipiAciklama" name="kursTipiAciklama" type="text" class="TextBox" style="width: 300px; height: 60px;">@(Html.Raw(Model.Aciklama))</textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="baslik" align="center">Yeni Tarih Tanımla</td>
                                </tr>
                                <tr>
                                    <td class="baslik">
                                        Yeni Başlangıç Tarihi
                                    </td>
                                    <td>
                                        <input id="kursTipiBasTarihHerPazartesi" class="kursTipiTarih" name="kursTipiTarih" value="herPazartesi" type="radio" />
                                        <label for="kursTipiBasTarihHerPazartesi">Her Pazartesi</label>
                                        <input id="kursTipiOzelTarih" class="kursTipiTarih" name="kursTipiTarih" value="ozel" type="radio" />
                                        <label for="kursTipiOzelTarih">Özel Tarih</label>

                                    </td>
                                    <td>
                                        <div id="divKursTipiOzelTarih" style="display: none;">
                                            ->
                                            <input id="kursTipiOzelTarihGiris" name="kursTipiOzelTarihGiris" class="TextBox" style="width: 60px;" type="text" />
                                            <input id="btnTarihEkle" type="button" value="Ekle" />
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="baslik">Özel Tarih Listesi</td>
                                    <td colspan="2">
                                        <div id="divOzelTarihListesi">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <input id="okulId" name="okulId" type="hidden" value="@ViewBag.OkulId" />
                                        <input id="ozelTarihListesi" name="ozelTarihListesi" type="hidden" value="" />
                                        <input id="btnGuncelle" type="submit" value="Güncelle" />

                                    </td>
                                    <td colspan="2">
                                        <input id="btnGoBack" type="button" onclick="location='@Url.Action("KursTipi", "OkulFiyatlari", new { okulId = ViewBag.OkulId })    '" value="Kurs Tipi Liste Sayfasına Dön" />
                                    </td>
                                </tr>
                            </table>
                        }
                    </td>
                </tr>
            </table>
        </td>
    </tr>

</table>

<script type="text/javascript">
    $(function () {

        kursTipi.init();
        kursTipi.tarihGoster('kursTipiOzelTarihGiris');
    })

</script>

WebApp/Areas/cms/Views/OkulFiyatlari/PromosyonKopyalaTesekkur.cshtml
@{
    ViewBag.Title = "Promosyon Kopyala Tesekkur";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}

@section HeaderWithContentPage{
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/fiyat_girisleri.js")"></script>
}

<br /><br /><br /><br /><br /><br />
<center><h2>Kopyalama işlemi tamamlandı!</h2></center>

<script type="text/javascript">
    $(function () {
        promosyonKopyalama.init();
    })

</script>

WebApp/Areas/cms/Views/OkulFiyatlari/PromosyonPaketPDFKopyalaTesekkur.cshtml
@{
    ViewBag.Title = "Paket Promosyon PDF Kopyalama Teşekkür";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}

@section HeaderWithContentPage{
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/fiyat_girisleri.js")"></script>
}

<br /><br /><br /><br /><br /><br />
<center><h2>Kopyalama işlemi tamamlandı!</h2></center>

<script type="text/javascript">
    $(function () {
        paketPromosyonPDFKopyalama.init();
    })

</script>

WebApp/Areas/cms/Views/OkulFiyatlari/_FiyatMenu.cshtml
@{
    string pageUrl = Request.RawUrl.ToString();
    string okulId = Request.QueryString["okulId"];
}
<div class="fiyatTab">
    <a href="@Url.Action("OkulEkUcretler", "OkulFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("OkulEkUcretler") ? "active" : "")">Standart Ücretler</a>   
    <a href="@Url.Action("KursTipi", "OkulFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("KursTipi") ? "active" : "")">Kurs Tipi</a>
    <a href="@Url.Action("FiyatTanimlari", "OkulFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("FiyatTanimlari") ? "active" : "")">Fiyat Tanımları</a>
    <a href="@Url.Action("PromosyonTanimlari", "OkulFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("PromosyonTanimlari") ? "active" : "")">Kurs Promosyonları</a>       
    <a href="@Url.Action("SummerSupplement", "OkulFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("SummerSupplement") ? "active" : "")">Summer Supplement</a>   
</div>