WebApp/Models/UlkeSehirViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class UlkeSehirViewModel
    {
        public IEnumerable<KeyValuePair<int, string>> Ulkeler { get; set; }
        public DilOkulu_Sehirler Sehir { get; set; }
        public List<DilOkulu_Sehirler> Sehirler { get; set; }
    }
}

WebApp/Areas/cms/Controllers/OkullarController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebApp.Core;
using WebApp.Models;
using WebApp.Models.Repositories;

namespace WebApp.Areas.cms.Controllers
{
    public class OkullarController : BaseController
    {
        //
        // GET: /cms/Okullar/
        #region Degiskenler
        private IMerkezRepository merkezRepository = null;
        private IOkulRepository okulRepository = null;
        private IEtiketRepository etiketRepository = null;
        private IGaleriRepository galeriRepository = null;
        private IEtiketIliskileriRepository etiketIliskileriRepository = null;
        private ISunulanProgramRepository sunulanProgramRepository = null;
        private GenericRepository<DilOkulu_Okullar> okulGenericRepository = null;
        private GenericRepository<DilOkulu_Etiketler> etiketlerGenericRepository = null;
        private GenericRepository<DilOkulu_EtiketIliskileri> etiketIliskileriGenericRepository = null;
        private string merkezBaslik = "";
        #endregion

        public ActionResult Index()
        {
            ViewBag.Merkezler = MerkezleriGetir();
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection fCollection)
        {
            #region FormCollection
            int merkezId = Convert.ToInt32(fCollection["SelectMerkez"]);
            #endregion

            okulRepository = new OkulRepository();
            var okullar = okulRepository.CMSOkullarListesi(merkezId);

            ViewBag.Merkezler = MerkezleriGetir();
            ViewBag.MerkezId = merkezId;

            return View(okullar);
        }

        public ActionResult yeni()
        {
            okulRepository = new OkulRepository();
            ViewBag.Merkezler = MerkezleriGetir();
            ViewBag.GaleriListesi = GaleriListesiGetir();
            ViewBag.SunulanProgramlar = SunulanProgramlariGetir();
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult yeni(FormCollection fCollection, string[] chk_Okultipi, string[] chk_KonaklamaTurleri, string[] chk_SunulanProgramlar)
        {
            #region FormCollection
            int dilId = Convert.ToInt32(fCollection["DilId"]);
            int ulkeId = Convert.ToInt32(fCollection["UlkeId"]);
            int sehirId = Convert.ToInt32(fCollection["SehirId"]);
            string seo_Keywords = fCollection["Seo_Keywords"];
            string seo_Descriptions = fCollection["Seo_Descriptions"];
            string okulKapasitesi = fCollection["OkulKapasitesi"];
            string sinifKapasitesi = fCollection["SinifKapasitesi"];
            string okulOlanaklari = fCollection["OkulOlanaklari"];
            string sosyalAktiviteler = fCollection["SosyalAktiviteler"];
            string baslik = fCollection["Baslik"];
            string icerik = fCollection["Icerik"];
            string harita = fCollection["Harita"];
            string streetView = fCollection["StreetView"];
            string videoUrl = fCollection["VideoUrl"];
            DateTime kayitTarihi = DateTime.Now;
            string onecikanOkul = fCollection["cbOnecikanOkul"];
            byte durumu = Convert.ToByte(fCollection["selectDurum"]);
            string selectMerkez = fCollection["SelectMerkez"];
            int galeriId = Convert.ToInt32(fCollection["selectGaleri"]);
            #endregion

            okulGenericRepository = new GenericRepository<DilOkulu_Okullar>();

            int merkezId = 0;
            if (!string.IsNullOrEmpty(selectMerkez))
            {
                merkezId = Convert.ToInt32(selectMerkez);

                merkezRepository = new MerkezRepository();
                merkezBaslik = merkezRepository.Liste().Where(m => m.Id == merkezId).FirstOrDefault().Baslik;
            }

            if (!string.IsNullOrEmpty(baslik) && merkezId > 0)
            {
                DilOkulu_Okullar okul = new DilOkulu_Okullar()
                {
                    MerkezId = merkezId,
                    DilId = dilId,
                    UlkeId = ulkeId,
                    SehirId = sehirId,
                    Baslik = baslik.Trim(),
                    Seo_Keywords = seo_Keywords,
                    Seo_Descriptions = seo_Descriptions,
                    OkulKapasitesi = okulKapasitesi,
                    SinifKapasitesi = sinifKapasitesi,
                    OkulOlanaklari = okulOlanaklari,
                    SosyalAktiviteler = sosyalAktiviteler,
                    OkulTipi = (chk_Okultipi != null && chk_Okultipi.Length > 0 ? string.Join(", ", chk_Okultipi) : ""),
                    KonaklamaTurleri = (chk_KonaklamaTurleri != null && chk_KonaklamaTurleri.Length > 0 ? string.Join(", ", chk_KonaklamaTurleri) : ""),
                    SunulanProgramlar = (chk_SunulanProgramlar != null && chk_SunulanProgramlar.Length > 0 ? string.Join(", ", chk_SunulanProgramlar) : ""),
                    Icerik = icerik,
                    Harita = harita,
                    StreetView = streetView,
                    GaleriId = galeriId,
                    VideoUrl = videoUrl,
                    Url = Tools.ReplaceTitle(merkezBaslik.Trim() + "-" + baslik.Trim()),
                    KayitTarihi = kayitTarihi,
                    OnecikanOkul = (!string.IsNullOrEmpty(onecikanOkul) && onecikanOkul.ToLower() == "on" ? true : false),
                    Durumu = durumu

                };

                DilOkulu_Okullar RetOkul = okulGenericRepository.Insert(okul);

                if (RetOkul != null)
                {
                    ViewBag.Status = "ok";
                }
                else
                {
                    ViewBag.Status = "err";
                }
            }
            else
            {
                ViewBag.Status = "err";
            }

            okulRepository = new OkulRepository(okulGenericRepository.dbContext);
            ViewBag.Merkezler = MerkezleriGetir();
            ViewBag.GaleriListesi = GaleriListesiGetir();
            ViewBag.SunulanProgramlar = SunulanProgramlariGetir();

            return View();
        }

        public ActionResult detay(int id)
        {
            okulRepository = new OkulRepository();
            var okul = okulRepository.Detay(id, new int[] { (int)GeneralVariables.Durum.Aktif, (int)GeneralVariables.Durum.Pasif });

            var etiketler = EtiketleriGetir();
            ViewBag.Merkezler = MerkezleriGetir();
            ViewBag.Etiketler = etiketler;
            ViewBag.IlislikiEtiketler = IliskiliEtiketleriGetir(etiketler, id);
            ViewBag.GaleriListesi = GaleriListesiGetir();
            ViewBag.SunulanProgramlar = SunulanProgramlariGetir();
            return View(okul);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult detay(FormCollection fCollection, HttpPostedFileBase file, string[] GenelBilgiMerkezdenAl, string[] chk_Okultipi, string[] chk_KonaklamaTurleri, string[] chk_SunulanProgramlar)
        {
            #region FormCollection
            int id = Convert.ToInt32(fCollection["Id"]);
            int dilId = Convert.ToInt32(fCollection["DilId"]);
            int ulkeId = Convert.ToInt32(fCollection["UlkeId"]);
            int sehirId = Convert.ToInt32(fCollection["SehirId"]);
            string seo_Keywords = fCollection["Seo_Keywords"];
            string seo_Descriptions = fCollection["Seo_Descriptions"];
            string okulKapasitesi = fCollection["OkulKapasitesi"];
            string sinifKapasitesi = fCollection["SinifKapasitesi"];
            string okulOlanaklari = fCollection["OkulOlanaklari"];
            string sosyalAktiviteler = fCollection["SosyalAktiviteler"];
            string baslik = fCollection["Baslik"];
            string icerik = fCollection["Icerik"];
            string harita = fCollection["Harita"];
            string streetView = fCollection["StreetView"];
            string videoUrl = fCollection["VideoUrl"];
            string onecikanOkul = fCollection["cbOnecikanOkul"];
            byte durumu = Convert.ToByte(fCollection["selectDurum"]);
            int merkezId = Convert.ToInt32(fCollection["SelectMerkez"]);
            int galeriId = Convert.ToInt32(fCollection["selectGaleri"]);
            string hfEtiketler = fCollection["hfEtiketler"];
            #endregion

            okulRepository = new OkulRepository();
            var okul = okulRepository.Detay(id, new int[] { (int)GeneralVariables.Durum.Aktif, (int)GeneralVariables.Durum.Pasif });
            merkezBaslik = okul.DilOkulu_Merkez.Baslik;
            okul.MerkezId = merkezId;
            okul.DilId = dilId;
            okul.UlkeId = ulkeId;
            okul.SehirId = sehirId;
            okul.Seo_Keywords = seo_Keywords;
            okul.Seo_Descriptions = seo_Descriptions;
            okul.OkulKapasitesi = okulKapasitesi;
            okul.SinifKapasitesi = sinifKapasitesi;
            okul.OkulOlanaklari = okulOlanaklari;
            okul.SosyalAktiviteler = sosyalAktiviteler;
            okul.OkulTipi = (chk_Okultipi != null && chk_Okultipi.Length > 0 ? string.Join(", ", chk_Okultipi) : "");
            okul.KonaklamaTurleri = (chk_KonaklamaTurleri != null && chk_KonaklamaTurleri.Length > 0 ? string.Join(", ", chk_KonaklamaTurleri) : "");
            okul.SunulanProgramlar = (chk_SunulanProgramlar != null && chk_SunulanProgramlar.Length > 0 ? string.Join(", ", chk_SunulanProgramlar) : "");
            okul.Baslik = baslik;
            okul.Icerik = icerik;
            okul.Harita = harita;
            okul.StreetView = streetView;
            okul.VideoUrl = videoUrl;
            okul.GaleriId = galeriId;
            okul.Url = Tools.ReplaceTitle(merkezBaslik + "-" + baslik.Trim());
            okul.Durumu = durumu;

            if (!string.IsNullOrEmpty(onecikanOkul))
            {

WebApp/Views/Okullar/Dil.cshtml
@model List<WebApp.Models.DilOkulu_Okullar>

@{
    string baslik = (!string.IsNullOrEmpty(ViewBag.Baslik) ? ViewBag.Baslik : "");
    string aciklama = (!string.IsNullOrEmpty(ViewBag.Aciklama) ? ViewBag.Aciklama : "");
    string resim = (!string.IsNullOrEmpty(ViewBag.Resim) ? ViewBag.Resim : "");
}

@{
    ViewBag.Title = "Dil Eğitimi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section metatags{
<meta name="keywords" content="@ViewBag.SeoKeywords" />
<meta name="description" content="@ViewBag.Description" />
}

@section PageTitle{
    <div class="topImg clearfix">
        <img src="@Url.Content("~/Assets/img/headers/header_3.jpg")" alt="About Us" />
        <h1><p><strong>@(baslik) Dil Eğitimi</strong></p></h1>
    </div>
}

<div class="course column c-67 clearfix">
    
    @if (!string.IsNullOrEmpty(aciklama))
    {
        <div class="box detaybox">
            <div class="boxInfo examInfo">
                <ul class="breadcrumb">
                    <li class="exm"><a href="@Url.Action("index","home")">Anasayfa</a></li>
                    <li class="exm">></li>
                    <li class="exm">@(baslik) Dil Eğitimi</li>
                </ul>
                <h2 class="title"><strong>@(baslik) Dil Eğitimi Hakkında Genel Bilgi</strong></h2>
                <div>
                    @if (!string.IsNullOrEmpty(resim))
                    {
                        <img class="fwidth2" src="@Url.Content(resim).Replace("tn_","")" alt="@(baslik) Dil Eğitimi" />
                    }
                    @Html.Raw(aciklama)
                </div>

                @if (Model != null && Model.Count > 0)
                {

                    var ulkeler = Model.Select(u => u.DilOkulu_Ulkeler).Distinct().OrderBy(u => u.Baslik).ToList();


                    <div class="okulsubeleri">
                        <h2><span class="okulsubebaslik">@(baslik) Dil Eğitimi Alabileceğiniz Ülkeler</span></h2>
                        @{
                    if (ulkeler != null && ulkeler.Count > 0)
                    {

                        <ul>
                            @foreach (var itemUlke in ulkeler)
{
    <li class="icdekili"><a href="@Url.Action("UlkeSehir", "okullar", new { url = itemUlke.Url })">@itemUlke.Baslik</a></li>
}
                            <li class="sonlibg"></li>
                        </ul>
                    }

                        }
                    </div>
                }
                else
                {
                    <strong>İçerik bulunamadı...</strong>
                }
            </div>
        </div>
    }

    
</div>

@Html.Partial("_RightColumn")

WebApp/Views/Okullar/MerkezDetay.cshtml
@model WebApp.Models.DilOkulu_Merkez
@{
    string listeTipi = ViewBag.ListeTipi;
    string resim = (!string.IsNullOrEmpty(ViewBag.Resim) ? ViewBag.Resim : "");
    string merkezBaslik = "";
    string okulBaslik = "";

}

@{
    ViewBag.Title = Model.Baslik + " | Dilokulu.com.tr<";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section PageTitle{
    <div class="topImg clearfix">
        <img src="@Url.Content("~/Assets/img/headers/header_3.jpg")" alt="" />
        <h1><p><strong>@(Model.Baslik)</strong></p></h1>
    </div>
}

@section metatags{
    <meta name="keywords" content="@Model.Seo_Keywords" />
    <meta name="description" content="@Model.Seo_Descriptions" />
}


<div class="blog column c-67 clearfix">
    <div class="box detaybox">
        <div class="boxInfo examInfo">
            <ul class="breadcrumb">
                <li class="exm"><a href="@Url.Action("index","home")">Anasayfa</a></li>
                <li class="exm">></li>
                <li class="exm">Okul: <a href="@Url.Action("MerkezDetay", "okullar", new { url = Model.Url })">@Model.Baslik</a></li>
            </ul>
            <div class="okulustbilgi">
                <div class="oubimg">
                    @if (!string.IsNullOrEmpty(Model.Logo))
                    {
                        <img src="@Url.Content("~/content/uploads/"+Model.Logo).Replace("tn_", "")" alt="@(Model.Baslik) Dil Okulu" />
                    }
                </div>
                <div class="oubotext"><div class="okuladhead">@Model.Baslik</div></div>
                @if (!string.IsNullOrEmpty(Model.KurulusTarihi))
                {
                    <div class="oubotext"><strong>Kuruluş Tarihi:</strong> @Model.KurulusTarihi</div>
                }

                @if (!string.IsNullOrEmpty(Model.Akreditasyonlar))
                {
                    <div class="oubotext"><strong>Akreditasyonlar:</strong> @(Model.Akreditasyonlar).</div>
                }
            </div>
            <div>
                @if (!string.IsNullOrEmpty(Model.GenelBilgi))
                {

                    @Html.Raw(Model.GenelBilgi)
                }
                <div style="float:left;margin-top:15px;">
                    <p style="font-size:13px;">

                        <strong> @Model.Baslik</strong> dil okullarının tüm listesine aşağıdan ulaşabilirsiniz.
                    </p>
                </div>
                @if (Model.DilOkulu_Okullar != null && Model.DilOkulu_Okullar.Count > 0)
                {
                    var ulkeler = Model.DilOkulu_Okullar.Where(u => u.DilOkulu_Ulkeler.Durumu == (int)WebApp.Core.GeneralVariables.Durum.Aktif).Select(u => new { UlkeId = u.DilOkulu_Ulkeler.Id, u.DilOkulu_Ulkeler.Baslik }).Distinct().ToList();
                    var okullar = Model.DilOkulu_Okullar.Where(o => o.Durumu == (int)WebApp.Core.GeneralVariables.Durum.Aktif).ToList();

                    foreach (var itemUlke in ulkeler)
                    {

                       
                        var ulkeOkullar = okullar.Where(o => o.UlkeId == itemUlke.UlkeId).OrderBy(o => o.Baslik).ToList();
                        if (ulkeOkullar != null && ulkeOkullar.Count > 0)
                        {
                            <div class="okulsubeleri">
                                <span class="okulsubebaslik">@itemUlke.Baslik</span>

                                <ul>
                                    @foreach (var itemOkul in ulkeOkullar)
                                    {
                                        merkezBaslik = WebApp.Core.Tools.ReplaceTitle(Model.Baslik);
                                        okulBaslik = WebApp.Core.Tools.ReplaceTitle(itemOkul.Baslik);
                                        <li class="icdekili"><a href="@Url.Action("detay", "okullar", new { merkez = merkezBaslik, url = okulBaslik })">@Model.Baslik - @itemOkul.Baslik</a></li>
                                    }
                                    <li class="sonlibg"></li>
                                </ul>

                            </div>
                        }

                      

                    }
                }
                @Html.Action("DigerOkullar", "Partial", new { merkezId = Model.Id })
                <div class="boxInfoPage">

                    <div class="searchCourse searchCoursePage clearfix">
                        @Html.Action("arama", "partial")
                    </div>

                    <div class="kampanyaPage" style="margin-top:10px;margin-left:10px;width:295px;">
                        @Html.Partial("_Banner300x250")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="sidebar" class="column c-33 clearfix">
    @Html.Partial("_SizeUlasalimFormu")
    @Html.Action("ResimGalerisi", "partial", new { id = ViewBag.GaleriId })
    <div class="clearfix">
        <div class="box">
            <h4 id="pdftext"><strong><a href="javascript:void(0)">Broşür</a></strong></h4>
            <h4 id="pdftexto"><strong><a href="javascript:void(0)">Fiyat Listesi</a></strong></h4>
            <h4 id="pdftextr"><strong><a href="javascript:void(0)">Promosyonlar</a></strong></h4>
            <div class="boxInfo">
                @if (!string.IsNullOrEmpty(Model.Brosur))
                {
                    <div id="pdficon"><a href="@Url.Content("~/content/uploads/" + Model.Brosur)" target="_blank" title="@(Model.Baslik) Broşürü"><img src="@Url.Content("~/assets/img/pdf_icon.png")" /></a></div>
                }
                else
                {
                    <div id="pdficon"><img src="@Url.Content("~/assets/img/pdf_icon_sb.png")" /></div>
                }
                @if (!string.IsNullOrEmpty(Model.FiyatListesi))
                {
                    <div id="pdficono"><a href="@Url.Content("~/content/uploads/" + Model.FiyatListesi)" target="_blank" title="@(Model.Baslik) Fiyat Listesi"><img src="@Url.Content("~/assets/img/pdf_icon.png")" /></a></div>
                }
                else
                {
                    <div id="pdficono"><img src="@Url.Content("~/assets/img/pdf_icon_sb.png")" /></div>
                }
                @if (!string.IsNullOrEmpty(Model.Promosyonlar))
                {
                    <div id="pdficon2"><a href="@Url.Content("~/content/uploads/" + Model.Promosyonlar)" target="_blank" title="@(Model.Baslik) Promosyonları"><img src="@Url.Content("~/assets/img/pdf_icon.png")" /></a></div>
                }
                else
                {
                    <div id="pdficon2"><img src="@Url.Content("~/assets/img/pdf_icon_sb.png")" /></div>
                }
            </div>
        </div>
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.EmbedVideo))
    {
        <div class="clearfix">
            <div class="box tour course">
                <h4><strong>Video</strong></h4>
                <div class="boxInfo clearfix">
                    @Html.Raw(ViewBag.EmbedVideo)
                </div>
            </div>
        </div>
    }
    <div class="clearfix">
        <div class="box">
            <h4 id="sosyalmedya"><strong>Sosyal Medya Hesapları</strong></h4>
            <div class="boxInfo">
                @if (!string.IsNullOrEmpty(Model.OkulSiteLink))
                {
                    <a href="@Model.OkulSiteLink" class="sosyalmedya website" target="_blank" rel="nofollow"><img src="@Url.Content("~/assets/img/website.png")"></a>
                }
                @if (!string.IsNullOrEmpty(Model.FacebookLink))
                {
                    <a href="@Model.FacebookLink" class="sosyalmedya" target="_blank" rel="nofollow"><img src="@Url.Content("~/assets/img/facebook.png")"></a>
                }
                @if (!string.IsNullOrEmpty(Model.TwitterLink))
                {
                    <a href="@Model.TwitterLink" class="sosyalmedya" target="_blank" rel="nofollow"><img src="@Url.Content("~/assets/img/twitter2.png")"></a>
                }
                @if (!string.IsNullOrEmpty(Model.YoutubeLink))
                {
                    <a href="@Model.YoutubeLink" class="sosyalmedya" target="_blank" rel="nofollow"><img src="@Url.Content("~/assets/img/youtube.png")"></a>
                }
            </div>
        </div>
    </div>

    @Html.Action("EnSonZiyaretEdilenOkullar", "partial")

    @Html.Action("etiketler", "partial")
</div>
<script type="text/javascript">
    $(function () {
        $(".overlay").hide();
    });
</script>

WebApp/Views/Okullar/UlkeSehir.cshtml
@model List<WebApp.Models.DilOkulu_Okullar>

@{
    string listeTipi = ViewBag.ListeTipi;
    string baslik = (!string.IsNullOrEmpty(ViewBag.Baslik) ? ViewBag.Baslik : "");
    string aciklama = (!string.IsNullOrEmpty(ViewBag.Aciklama) ? ViewBag.Aciklama : "");

    string vizeBilgileri = (!string.IsNullOrEmpty(ViewBag.VizeBilgileri) ? ViewBag.VizeBilgileri : "");
    string calismaIzni = (!string.IsNullOrEmpty(ViewBag.CalismaIzni) ? ViewBag.CalismaIzni : "");
    string yasamGiderleri = (!string.IsNullOrEmpty(ViewBag.YasamGiderleri) ? ViewBag.YasamGiderleri : "");
    string ulasim = (!string.IsNullOrEmpty(ViewBag.Ulasim) ? ViewBag.Ulasim : "");
    string saglikSistemi = (!string.IsNullOrEmpty(ViewBag.SaglikSistemi) ? ViewBag.SaglikSistemi : "");


    string resim = (!string.IsNullOrEmpty(ViewBag.Resim) ? ViewBag.Resim : "");
    string merkezBaslik = "";
    string okulBaslik = "";

    if (!string.IsNullOrEmpty(listeTipi))
    {
        switch (listeTipi)
        {
            case "Sehir":
                break;
            case "Ulke":
                break;
        }
    }

}

@{
    ViewBag.Title = baslik + " Dil Okulları ve Dil Eğitimi | Dilokulu.com.tr";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@section PageTitle{
    <div class="topImg clearfix">
        <img src="@Url.Content("~/Assets/img/headers/header_3.jpg")" alt="About Us" />
        <h1><p><strong>@(baslik) Dil Okulları</strong></p></h1>
    </div>
}

@section metatags{
    <meta name="keywords" content="@ViewBag.SeoKeywords" />
    <meta name="description" content="@ViewBag.Description" />
}

<div class="course column c-67 clearfix">
    <div class="box detaybox">
        <div class="boxInfo examInfo">
            <ul class="breadcrumb">
                <li class="exm"><a href="@Url.Action("index","home")">Anasayfa</a></li>
                <li class="exm">></li>
                <li class="exm">@(baslik) Dil Okulları</li>
            </ul>
            @if (!string.IsNullOrEmpty(aciklama))
            {
                <h2 class="title"><strong>@(baslik) Dil Okulları Hakkında Genel Bilgi</strong></h2>
                <div>
                    @if (!string.IsNullOrEmpty(resim))
                    {
                        <img class="fwidth2" src="@Url.Content(resim).Replace("tn_","")" alt="@(baslik) Dil Eğitimi" />
                    }
                    @Html.Raw(aciklama)
                </div>

            }


            <div class="">
                @if (!string.IsNullOrEmpty(vizeBilgileri))
                {
                    <div class="ulkesehirbox">
                        <h2><strong>Vize Bilgileri</strong></h2>
                        <div class="boxInfo" style="padding: 0px;">
                            <p>
                                @Html.Raw(vizeBilgileri)
                            </p>
                        </div>
                    </div>
                }
                @if (!string.IsNullOrEmpty(calismaIzni))
                {
                    <div class="ulkesehirbox">
                        <h2><strong>Çalışma İzni</strong></h2>
                        <div class="boxInfo" style="padding: 0px;">
                            <p>
                                @Html.Raw(calismaIzni)
                            </p>
                        </div>
                    </div>
                }
                @if (!string.IsNullOrEmpty(yasamGiderleri))
                {
                    <div class="ulkesehirbox">
                        <h2><strong>Yaşam Giderleri</strong></h2>
                        <div class="boxInfo" style="padding: 0px;">
                            <p>
                                @Html.Raw(yasamGiderleri)
                            </p>
                        </div>
                    </div>
                }
                @if (!string.IsNullOrEmpty(ulasim))
                {
                    <div class="ulkesehirbox">
                        <h2><strong>Ulaşım</strong></h2>
                        <div class="boxInfo" style="padding: 0px;">
                            <p>
                                @Html.Raw(ulasim)
                            </p>
                        </div>
                    </div>
                }
                @if (!string.IsNullOrEmpty(saglikSistemi))
                {
                    <div class="ulkesehirbox">
                        <h2><strong>Sağlık Sistemi</strong></h2>
                        <div class="boxInfo" style="padding: 0px;">
                            <p>
                                @Html.Raw(saglikSistemi)
                            </p>
                        </div>
                    </div>
                }
            </div>



            <h2 class="title"><strong>@(baslik) Dil Okulları</strong></h2>

            @if (Model != null && Model.Count > 0)
            {

                var sehirler = Model.Select(o => o.DilOkulu_Sehirler).OrderBy(s => s.Baslik).ToList().Distinct();
                foreach (var item in sehirler)
                {
                    <div class="okulsubeleri">
                        <h3><span class="okulsubebaslik"><a href="@Url.Action("UlkeSehir", "Okullar", new { url=item.Url})" style="color: #9bb70d !important;">@item.Baslik</a></span></h3>
                        @{
                    var sehirOkullar = Model.Where(o => o.SehirId == item.Id).OrderBy(o => o.DilOkulu_Merkez.Baslik).ToList();
                    if (sehirOkullar != null && sehirOkullar.Count > 0)
                    {

                        <ul>
                            @foreach (var itemOkul in sehirOkullar)
                            {
                                merkezBaslik = WebApp.Core.Tools.ReplaceTitle(itemOkul.DilOkulu_Merkez.Baslik);
                                okulBaslik = WebApp.Core.Tools.ReplaceTitle(itemOkul.Baslik);
                                <li class="icdekili"><a href="@Url.Action("detay", "okullar", new { merkez = merkezBaslik, url = okulBaslik })">@itemOkul.DilOkulu_Merkez.Baslik - @itemOkul.Baslik</a></li>
                            }
                            <li class="sonlibg"></li>
                        </ul>
                    }

                        }
                    </div>
                }

            }
            else
            {
                <strong>İçerik bulunamadı...</strong>
            }
        </div>
    </div>
</div>

@Html.Partial("_RightColumn")