WebApp/Controllers/OgrenciYorumlariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Core;
using WebApp.Models.Repositories;

namespace WebApp.Controllers
{
    public class OgrenciYorumlariController : Controller
    {
        //
        // GET: /OgrenciYorumlari/

        #region Degiskenler
        private IMakaleRepository makaleRepository = null;
        #endregion

        public ActionResult Index()
        {
            makaleRepository = new MakaleRepository();
            var makaleler = makaleRepository.Liste()
                .Where(oy => oy.Durumu == (int)GeneralVariables.Durum.Aktif && oy.KategoriId == (int)GeneralVariables.MakaleKategorileri.Ogrenci)
                .OrderByDescending(oy => oy.KayitTarihi)
                .ToList();
            return View(makaleler);
        }

        public ActionResult Detay(string title = "")
        {
            if (!string.IsNullOrEmpty(title))
            {
                makaleRepository = new MakaleRepository();
                var makale = makaleRepository.Detay(title, new[] { (int)GeneralVariables.Durum.Aktif });
                return View(makale);
            }
            else
            {
                return View();
            }
        }

    }
}

WebApp/Views/OgrenciYorumlari/Detay.cshtml
@model WebApp.Models.DilOkulu_Makaleler
@{
    ViewBag.Title = Model.Baslik+ " | Dilokulu.com.tr";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section PageTitle{
    <div class="topImg clearfix">
        <img src="@Url.Content("~/Assets/img/headers/header_2.jpg")" alt="Öğrenci Yorumları" />
        <p><strong>Öğreni Yorumları</strong></p>
    </div>
}

@if (Model != null)
{
    <div class="blog column c-67 clearfix">

        <div class="box">
            <h4>@Model.Baslik</h4>
            <div class="boxInfo examInfo">
                <ul class="breadcrumb">
                    <li class="exm"><a href="@Url.Action("index","home")">Anasayfa</a></li>
                    <li class="exm">></li>
                    <li class="exm"><a href="@Url.Action("index", "OgrenciYorumlari")">Öğrenci Yorumları</a></li>
                    <li class="exm">></li>
                    <li class="exm"><a href="@Url.Action("detay", "OgrenciYorumlari", new { title = Model.Url })">@Model.Baslik</a></li>
                </ul>
                <div>
                    @if (!string.IsNullOrEmpty(Model.ResimUrl))
                    {
                        <img class="fwidth2" src="@Url.Content(Model.ResimUrl)" alt="@Model.Baslik">
                    }
                    <p>
                        @Html.Raw(Model.Icerik)
                    </p>
                </div>
                <ul style="font-size: 13px; font-weight: 700;">
                    <li class="proExm">@Model.DilOkulu_Yazarlar.AdSoyad</li>
                </ul>
            </div>
        </div>
    </div>

    @Html.Partial("_RightColumn")

}

WebApp/Views/OgrenciYorumlari/Index.cshtml
@model List<WebApp.Models.DilOkulu_Makaleler>
@{
    ViewBag.Title = "Öğrenci Yorumları";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section metatags{
    <meta name="keywords" content="" />
    <meta name="description" content="" />
}

@section PageTitle{
    <div class="topImg clearfix">
        <img src="@Url.Content("~/assets/img/headers/header_2.jpg")" alt="About Us">
        <p><strong>MAKALELER</strong></p>
    </div>
}

<div class="course column c-67 clearfix">

    @if (Model != null && Model.Count > 0)
    {


        foreach (var item in Model)
        {
            <div class="box">
                <ul class="courseId">
                    <li><a href="@Url.Action("detay", "OgrenciYorumlari", new { title = item.Url })" title="@(item.Baslik)">@(item.Baslik)</a></li>
                    <li></li>
                </ul>
                <div class="boxInfo">
                    <p id="arama_list">
                        <a href="@Url.Action("detay", "OgrenciYorumlari", new { title = item.Url })" title="@item.Baslik">
                            @if (!string.IsNullOrEmpty(item.ResimThumbUrl))
                            {
                                <img class="fwidth3" src="@Url.Content(item.ResimThumbUrl)" alt="@item.Baslik" />
                            }

                        </a>
                        @Html.Raw(item.Ozet)
                    </p>
                </div>
                <div class="courseInfo">
                    <p class="courseTime">&nbsp;</p>
                    <ul>
                        <li>
                            <a href="@Url.Action("detay", "OgrenciYorumlari", new { title = item.Url })" title="@item.Baslik"><strong>Detaylı Bilgi</strong></a>
                        </li>
                    </ul>
                </div>
            </div>
        }
        @*<ul class="pgNr">
                <li><a href="#"> 1</a></li>
                <li><a href="#"> 2</a></li>
                <li><a href="#"> 3</a></li>
                <li><a href="#"> 4</a></li>
                <li><a href="#"> ></a></li>
            </ul>*@

    }
    else
    {
        <strong>İçerik bulunamadı...</strong>
    }
</div>

@Html.Partial("_RightColumn")