WebApp/Areas/cms/Controllers/KonaklamaFiyatlariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Core;
using WebApp.Models;
using WebApp.Models.Repositories;

namespace WebApp.Areas.cms.Controllers
{
    public class KonaklamaFiyatlariController : Controller
    {
        //
        // GET: /cms/KonaklamaFiyatlari/

        #region Degiskenler
        private IOkulRepository okulRepository = null;
        private IKonaklamaKategoriRepository konaklamaKategoriRepository = null;
        private IKonaklamaTipiRepository konaklamaTipiRepository = null;
        private IKonaklamaTipiFiyatlandirmalariRepository konaklamaTipiFiyatlandirmalariRepository = null;
        private IKonaklamaTipiPromosyonTanimlariRepository konaklamaTipiPromosyonTanimlariRepository = null;
        private IKonaklamaTipiEkUcretleriRepository konaklamaTipiEkUcretleriRepository = null;
        private GenericRepository<DilOkulu_KonaklamaTipleri> generickonaklamaTipleri = null;
        private GenericRepository<DilOkulu_KonaklamaTipiFiyatlandirmalari> genericKonaklamaTipiFiyatlandirmalari = null;
        private GenericRepository<DilOkulu_KonaklamaTipiPromosyonTanimlari> genericKonaklamaTipiPromosyonTanimlari = null;
        private GenericRepository<DilOkulu_KonaklamaTipiEkUcretleri> genericKonaklamaTipiEkUcretleri = null;
        private DilOkulu_Okullar okul = null;
        private List<DilOkulu_Okullar> okullar = null;
        #endregion

        #region KonaklamaTipleri
        public ActionResult KonaklamaTipi(int okulId = 0)
        {
            konaklamaKategoriRepository = new KonaklamaKategoriRepository();
            var konaklamaKategorileri = konaklamaKategoriRepository.Liste()
                .Where(kk => kk.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kk => kk.Baslik).ToList();

            ViewBag.KonaklamaKategorileri = konaklamaKategorileri;
            ViewBag.OkulId = okulId.ToString();

            konaklamaTipiRepository = new KonaklamaTipiRepository();
            var konaklamaTipleri = konaklamaTipiRepository.Liste().Where(kt => kt.OkulId == okulId && kt.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kt => kt.Baslik).ToList();

            return View(konaklamaTipleri);
        }

        public ActionResult KonaklamaTipiEdit(int id = 0, int okulId = 0)
        {
            #region Kurs Kategorileri
            konaklamaKategoriRepository = new KonaklamaKategoriRepository();
            var konaklamaKategorileri = konaklamaKategoriRepository.Liste()
                .Where(kk => kk.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kk => kk.Baslik).ToList();

            ViewBag.KonaklamaKategorileri = konaklamaKategorileri;
            #endregion

            ViewBag.OkulId = okulId.ToString();

            konaklamaTipiRepository = new KonaklamaTipiRepository();
            var konaklamaTipi = konaklamaTipiRepository.Detay(id, new int[] { (byte)GeneralVariables.Durum.Aktif });

            return View(konaklamaTipi);
        }

        [HttpPost]
        public ActionResult KonaklamaTipiEdit(FormCollection fColl, int id = 0, int okulId = 0)
        {
            #region Kurs Kategorileri
            konaklamaKategoriRepository = new KonaklamaKategoriRepository();
            var konaklamaKategorileri = konaklamaKategoriRepository.Liste()
                .Where(kk => kk.Durumu != (byte)GeneralVariables.Durum.Silindi).OrderBy(kk => kk.Baslik).ToList();

            ViewBag.KonaklamaKategorileri = konaklamaKategorileri;

            #endregion

            #region Variables
            var konaklamaKategoriId = Convert.ToInt32("0" + fColl["konaklamaKategorisi"]);
            var baslik = fColl["baslik"];
            var aciklama = HttpUtility.UrlDecode(fColl["kursTipiAciklama"]);
            var konaklamaTipiTarih = fColl["konaklamaTipiTarih"];
            var ozelTarihListesi = Request["ozelTarihListesi"].TrimEnd('|');
            bool basTarihiYilBoyu = false;
            bool basTarihiOzel = false;
            #endregion

            ViewBag.OkulId = okulId.ToString();

            konaklamaTipiRepository = new KonaklamaTipiRepository();
            var konaklamaTipi = konaklamaTipiRepository.Detay(id, new int[] { (byte)GeneralVariables.Durum.Aktif });
            if (konaklamaTipi != null)
            {
                konaklamaTipi.KonaklamaKategoriId = konaklamaKategoriId;
                konaklamaTipi.Baslik = baslik;
                konaklamaTipi.Aciklama = aciklama;
                if (!string.IsNullOrEmpty(konaklamaTipiTarih))
                {
                    if (konaklamaTipiTarih == "ozel")
                    {
                        basTarihiOzel = true;
                        if (!string.IsNullOrEmpty(ozelTarihListesi))
                        {
                            konaklamaTipi.BasTarihiYilBoyu = false;
                            konaklamaTipi.BasTarihiOzel = true;
                            konaklamaTipi.OzelTarihListesi = ozelTarihListesi;
                        }
                    }
                    else
                    {
                        basTarihiYilBoyu = true;
                        konaklamaTipi.BasTarihiYilBoyu = true;
                        konaklamaTipi.BasTarihiOzel = false;
                        konaklamaTipi.OzelTarihListesi = string.Empty;
                    }
                }

                generickonaklamaTipleri = new GenericRepository<DilOkulu_KonaklamaTipleri>(konaklamaTipiRepository.DBContext);
                var retVal = generickonaklamaTipleri.Update(konaklamaTipi);
                if (retVal != null)
                {
                    ViewBag.Status = "ok";
                }
                else
                {
                    ViewBag.Status = "error";
                }

            }
            return View(konaklamaTipi);
        }

        /// <summary>
        /// Ajax Insert
        /// </summary>
        /// <returns></returns>
        public JsonResult KonaklamaTipiEkle()
        {
            #region Variables
            string status = "error";
            string message = "";
            var okulId = Convert.ToInt32("0" + Request["okulId"]);
            var baslik = Request["baslik"];
            var konaklamaKategoriId = Convert.ToInt32("0" + Request["konaklamaKategoriId"]);
            var basTarihiStatus = Request["basTarihiStatus"];
            var ozelTarihListesi = Request["ozelTarihListesi"].TrimEnd('|');
            var aciklama = HttpUtility.UrlDecode(Request["aciklama"]);

            bool basTarihiYilBoyu = false;
            bool basTarihiOzel = false;

            if (basTarihiStatus == "ozel")
            {
                basTarihiOzel = true;
            }
            else
            {
                basTarihiYilBoyu = true;
            }
            #endregion

            if (okulId > 0 && !string.IsNullOrEmpty(baslik) && konaklamaKategoriId > 0)
            {
                konaklamaTipiRepository = new KonaklamaTipiRepository();
                DilOkulu_KonaklamaTipleri yeniTip = new DilOkulu_KonaklamaTipleri()
                {
                    OkulId = okulId,
                    Baslik = baslik,
                    KonaklamaKategoriId = konaklamaKategoriId,
                    Aciklama = aciklama,
                    KayitTarihi = DateTime.Now,
                    BasTarihiYilBoyu = basTarihiYilBoyu,
                    BasTarihiOzel = basTarihiOzel,
                    OzelTarihListesi = ozelTarihListesi,
                    Durumu = (byte)GeneralVariables.Durum.Aktif
                };

                generickonaklamaTipleri = new GenericRepository<DilOkulu_KonaklamaTipleri>();
                var retVal = generickonaklamaTipleri.Insert(yeniTip);
                if (retVal != null)
                {
                    status = "ok";
                }
                else
                {
                    message = "Kayıt işlemi sırasında problem ile karşılaşıldı!";
                }
            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Ajax Delete
        /// </summary>
        /// <returns></returns>
        public JsonResult KonaklamaTipiSil(int id = 0)
        {
            string status = "error";
            string message = "Hata:Silme işlemi yapılamadı!";

            if (id > 0)
            {
                konaklamaTipiRepository = new KonaklamaTipiRepository();
                var konaklamaTipi = konaklamaTipiRepository.Liste().Where(kt => kt.Id == id).FirstOrDefault(); ;
                //&& kt.Durumu != (byte)GeneralVariables.Durum.Silindi
                if (konaklamaTipi != null)
                {
                    generickonaklamaTipleri = new GenericRepository<DilOkulu_KonaklamaTipleri>(konaklamaTipiRepository.DBContext);
                    var retVal = generickonaklamaTipleri.Delete(konaklamaTipi);
                    if (retVal > 0)
                    {
                        status = "ok";
                        message = "Kayıt silindi!";
                    }
                    else
                    {
                        message = "Hata:Silme işlemi yapılamadı!";
                    }

                }
            }

            return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Tanımlı Fiyat modelini bulan metod
        /// </summary>
        /// <returns></returns>
        public JsonResult KonaklamaTipiFiyatModeliBul()
        {
            #region Variables
            string status = "error";
            var konaklamaTipiId = Convert.ToInt32("0" + Request["konaklamaTipiId"]);
            var fiyatlandirmaModelId = 0;
            #endregion

            konaklamaTipiFiyatlandirmalariRepository = new KonaklamaTipiFiyatlandirmalariRepository();

WebApp/Areas/cms/Views/KonaklamaFiyatlari/KonaklamaEkUcretKopyala.cshtml
@using WebApp.Models
@{
    ViewBag.Title = "Konaklama Ek Ücret Kopyalama";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";

    List<DilOkulu_Okullar> okullar = null;
    if (ViewBag.Okullar != null)
    {
        okullar = (List<DilOkulu_Okullar>)ViewBag.Okullar;
    }

}

@section SectionBeforeWrapper{
    @Html.Partial("_Modals")
}

@section HeaderWithContentPage{
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/konaklama_girisleri.js")"></script>
    <style>
        .promotionList {
            list-style-type: none;
            padding: 0px;
            margin: 0px;
        }

            .promotionList h4 {
                margin: 2px;
                font-size: 12px !important;
            }

            .promotionList ol {
                margin: 0px 0px 0px -35px;
            }
    </style>
}

<h2>Konaklama Ek Ücret Kopyalama</h2>
@{
    var routeValues = new RouteValueDictionary();
    routeValues.Add("konaklamaTipiId", ViewBag.KonaklamaTipiId);
    routeValues.Add("merkezId", ViewBag.MerkezId);
    routeValues.Add("okulId", ViewBag.OkulId);

}
@using (Html.BeginForm("KonaklamaEkUcretKopyala", "KonaklamaFiyatlari", routeValues, FormMethod.Post, null))
{
    if (okullar != null && okullar.Count > 0)
    {
        <ul class="promotionList">
            @foreach (var item in okullar)
            {
                <li>
                    <h4>@item.Baslik</h4>
                    @if (item.DilOkulu_KonaklamaTipleri.Count > 0)
                    {
                        foreach (var itemKonaklamaTipi in item.DilOkulu_KonaklamaTipleri)
                        {
                            if (ViewBag.KursTipiId != itemKonaklamaTipi.Id)
                            {
                                <ol><input id="cbxKursTipi_@itemKonaklamaTipi.Id" name="konaklamaTipleri" value="@itemKonaklamaTipi.Id" class="kursTipleri" type="checkbox" /><label for="cbxKursTipi_@itemKonaklamaTipi.Id">@itemKonaklamaTipi.Baslik</label></ol>
                            }

                        }
                    }
                    else
                    {
                        <ol><b style="color:red">Empty</b></ol>
                    }


                </li>
            }
        </ul>
        <input id="btnKonaklamaEkUcretKopyala" type="submit" value="Kopyalama İşlemine Başla!" />
        <input id="btnSubmit" type="submit" value="" style="display:none" />
    }
    <input id="hfSecilenKonaklamaTipiId" value="@ViewBag.KonaklamaTipiId" type="hidden" />
}
<script type="text/javascript">
    $(function () {
        konaklamaEkUcretKopyalama.init();
    })

</script>

WebApp/Areas/cms/Views/KonaklamaFiyatlari/KonaklamaEkUcretler.cshtml
@using WebApp.Models
@model  List<DilOkulu_KonaklamaTipiEkUcretleri>
@{

    List<WebApp.Models.DilOkulu_KonaklamaTipleri> konaklamaTipleri = null;
    if (ViewBag.KonaklamaTipleri != null)
    {
        konaklamaTipleri = (List<WebApp.Models.DilOkulu_KonaklamaTipleri>)ViewBag.KonaklamaTipleri;
    }
}

@{
    ViewBag.Title = "Konaklama Ek Ücretler";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}

@section HeaderWithContentPage{
    <link href="@Url.Content("~/Areas/cms/Assets/css/smoothness/jquery-ui-1.11.4.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-ui-1.11.4.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/datepicker-tr.js")"></script>
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/konaklama_girisleri.js")"></script>

    <!-- Add mousewheel plugin (this is optional) -->
    <script src="@Url.Content("~/Areas/cms/Assets/fancybox/lib/jquery.mousewheel-3.0.6.pack.js")"></script>
    <!-- Add fancyBox -->
    <link rel="stylesheet" href="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.css?v=2.1.5")" type="text/css" media="screen" />
    <script type="text/javascript" src="@Url.Content("~/Areas/cms/Assets/fancybox/source/jquery.fancybox.pack.js?v=2.1.5")"></script>

<script type="text/javascript">
    $(function () {
        var ProcessStatus = '@Html.Raw(ViewBag.Status)';

        if (ProcessStatus == "ok") {
            GeneralObj.DilokuluMessageBox.init({ status: 'ok', message: 'Kayıt işlemi gerçekleşti.' });
        }

        $('.fancybox').fancybox({
            width: 420,
            height: 590,
            fitToView: false,
            autoSize: false,
            afterClose: function () {

                // location.reload();
            },
            helpers: {
                overlay: { closeClick: false } // prevents closing when clicking OUTSIDE fancybox
            }

        });
    })
</script>

}


@section SectionBeforeWrapper{
    @Html.Partial("_Modals")
}


<div id="divStatusBox" style="">
    <span id="spanMessageText"></span>
</div>
<table cellpadding="0" cellspacing="0" style="width: 100%;">
    <tr>
        <td class="MasterRow3_Column1">
            @Html.Partial("_OkullarMunu")
        </td>

        <td class="MasterRow3_Column2">
            @Html.Action("_OkulOzetBilgileri")
            @Html.Partial("_KonaklamaMenu")

            <table cellpadding="0" cellspacing="0" class="OrtaMenu">
                <tr>
                    <td class="OrtaMenuRow">
                        <table cellpadding="0" border="0" cellspacing="0" class="fiyatTable" style="width:755px;">
                            @using (Html.BeginForm("KonaklamaEkUcretler", "KonaklamaFiyatlari", new { okulId = ViewBag.OkulId, konaklamaTipiId = ViewBag.KonaklamaTipiId }, FormMethod.Post))
                            {
                                <tr>
                                    <td class="baslik">
                                        Konaklama Tipleri<span class="SpanZorunluAlan">*</span>
                                    </td>
                                    <td>
                                        <select id="konaklamaTipi" name="konaklamaTipi" class="DropDownList">
                                            <option value="">Seçin...</option>
                                            @foreach (var item in konaklamaTipleri)
                                            {
                                                <option value="@item.Id" @(ViewBag.KonaklamaTipiId == item.Id ? "selected" : "")>@item.Baslik</option>
                                            }
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <table cellpadding="0" border="0" cellspacing="0">
                                            <tr>

                                                <td class="baslik">
                                                    Başlangıç Tarihi<span class="SpanZorunluAlan">*</span>
                                                </td>

                                                <td class="baslik">
                                                    Bitiş Tarihi<span class="SpanZorunluAlan">*</span>
                                                </td>
                                                <td class="baslik">
                                                    Maks. Hafta
                                                </td>
                                                <td class="baslik">
                                                    Haftalık Ek Ücret<span class="SpanZorunluAlan">*</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <input id="BaslangicTarihi" name="BaslangicTarihi" value="" type="text" style="width:80px;" />
                                                </td>

                                                <td>
                                                    <input id="BititisTarihi" name="BititisTarihi" value="" type="text" style="width:80px;" />
                                                </td>
                                                <td>
                                                    <select id="MaksimunHafta" name="MaksimunHafta" class="DropDownList">
                                                        <option value="52">Seçin...</option>
                                                        @for (int i = 1; i <= 52; i++)
                                                        {
                                                            <option value="@i.ToString()">@i.ToString() Hafta</option>
                                                        }
                                                    </select>
                                                </td>
                                                <td>
                                                    <input id="Fiyat" name="Fiyat" value="" type="text" style="width:80px;" />
                                                    <input id="okulId" name="okulId" type="hidden" value="@ViewBag.OkulId" />
                                                    <input id="btnHavaAlaniEkle" type="submit" value="Ekle" />
                                                    @if (Model != null && Model.Count > 0)
                                                    {
                                                        <input type="button" id="btnKonaklamaEkUcret_Kopyala" href="@Url.Action("KonaklamaEkUcretKopyala", "KonaklamaFiyatlari", new { konaklamaTipiId = Model[0].DilOkulu_KonaklamaTipleri.Id, merkezId = Model[0].DilOkulu_KonaklamaTipleri.DilOkulu_Okullar.MerkezId, okulId = Model[0].DilOkulu_KonaklamaTipleri.OkulId })" class="fancybox fancybox.iframe" data-promosyontipiid="1" value="Kopyala">
                                                    }
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                               
                            }
                            <tr>
                                <td class="baslik" colspan="2">
                                    Ek Ücret Listesi
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    @if (Model != null && Model.Count > 0)
                                    {
                                        <table id="hor-zebra" class="tblHavaAlanlari" style="width:100%;margin: 0px !important;">
                                            <thead><tr><th>BAŞLANGIÇ TARİHİ</th><th>BİTİŞ TARİHİ</th><th>MAKS. HAFTA</th><th>FİYAT</th><th>#</th></tr></thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td class="baslik">@String.Format("{0:dd.MM.yyyy}", item.BaslangicTarihi)</td>
                                                        <td class="baslik">@String.Format("{0:dd.MM.yyyy}", item.BititisTarihi)</td>
                                                        <td class="baslik">@item.MaksimumHafta</td>
                                                        <td>@item.Fiyat</td>
                                                        <td><a href="javascript:;" onclick="konaklamaEkUcret.ucretSil('@item.Id')">Sil</a></td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    }

                                </td>
                            </tr>
                        </table>
                        <div>
                            <hr>
                            <b>Nasıl Kullanılır?</b><br>
                            2 tarih arasına denk gelen bir konaklama seçimi var ise, kurs ücretine ilave fark eklenilmektedir. Maksimum Hafta alanı ise, eğer 2 tarih arasında örn maks 10 hafta seçilmiş ise ve maks hafta 9 olarak girilmiş ise fark fiyat uygulanmayacağı ifade edilmiş oluyor. Her hangi bir hafta belirtilmez ise sadece 2 tarih arası dikkate alınmaktadır.
                        </div>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>
<script type="text/javascript">
    $(function () {

        $(function () {
            konaklamaTipi.tarihGoster('BaslangicTarihi');
            konaklamaTipi.tarihGoster('BititisTarihi');

            konaklamaEkUcret.konaklamaTipiChange('@Url.Action("KonaklamaEkUcretler", "KonaklamaFiyatlari", new { okulId = ViewBag.OkulId })');
        })
    })

</script>

WebApp/Areas/cms/Views/KonaklamaFiyatlari/KonaklamaTipi.cshtml
@model List<WebApp.Models.DilOkulu_KonaklamaTipleri>
@{
    ViewBag.Title = "Konaklama Tiplari";
    Layout = "~/Areas/cms/Views/Shared/_CMSLayout.cshtml";
}

@section HeaderWithContentPage{
    <link href="@Url.Content("~/Areas/cms/Assets/css/smoothness/jquery-ui-1.11.4.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-1.10.2.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/jquery-ui-1.11.4.js")"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/datepicker-tr.js")"></script>
    <script src="~/Areas/cms/Assets/js/dilokulu.js"></script>
    <script src="@Url.Content("~/Areas/cms/Assets/js/konaklama_girisleri.js")"></script>
}


@section SectionBeforeWrapper{
    @Html.Partial("_Modals")
}


<div id="divStatusBox" style="">
    <span id="spanMessageText"></span>
</div>
<table cellpadding="0" cellspacing="0" style="width: 100%;">
    <tr>
        <td class="MasterRow3_Column1">
            @Html.Partial("_OkullarMunu")
        </td>

        <td class="MasterRow3_Column2">
            @Html.Action("_OkulOzetBilgileri")
            @Html.Partial("_KonaklamaMenu")
            @Html.Partial("_KonaklamaTipiEkle")

            <!--Konaklama Tipi Listesi-->

            <table id="hor-zebra" class="tblFiyatListesi" style="width: 780px; margin: 0px;">
                <caption>
                    <div style="font-size:15px;">
                        <strong>Konaklama Tipi Tistesi</strong>
                    </div>
                </caption>
                <thead>
                    <tr>
                        <th scope="col">Kategori</th>
                        <th>Konaklama Tipi</th>
                        <th>Başlangıç Tarihleri</th>
                        <th>Açıklama</th>
                        <th colspan="2"><input id="Button1" type="button" onclick="konaklamaTipi.tumKonaklamaTipiListesiniSil();" value="Tüm Fiyat Listesini Sil" /></th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model != null && Model != null && Model.Count > 0)
                    {
                        int Counter = 2;
                        foreach (var item in Model)
                        {
                            <tr class="fieldset" @(Counter % 2 == 0 ? "class=odd" : "")>
                                <td valign="top">@item.DilOkulu_KonaklamaKategorileri.Baslik <input id="hfId" value="@item.Id" type="hidden" /></td>
                                <td valign="top">
                                    @item.Baslik
                                </td>
                                <td valign="top">
                                    @if (Convert.ToBoolean(item.BasTarihiYilBoyu))
                                    {
                                    @Html.Raw("Yıl Boyu")
                                    }
                                    else
                                    {
                                        foreach (var tarih in item.OzelTarihListesi.Split('|'))
                                        {
                                    @Html.Raw(tarih + "<br/>")
                                        }
                                    }
                                </td>
                                <td valign="top">
                                    <div style="max-width:200px;">
                                        @Html.Raw(item.Aciklama)
                                    </div>
                                </td>
                                <td valign="top">
                                    <div style="line-height:20px;">
                                        <a href="@Url.Action("FiyatTanimlari", "KonaklamaFiyatlari", new { okulId = item.OkulId, konaklamaTipiId = item.Id })">Fiyatlar</a><br />
                                        <a href="@Url.Action("PromosyonTanimlari", "KonaklamaFiyatlari", new { okulId = item.OkulId, konaklamaTipiId = item.Id })">Promosyonlar</a>
                                    </div>
                                </td>
                                <td>
                                    <a href="@Url.Action("KonaklamaTipiEdit", "KonaklamaFiyatlari", new { id = item.Id, okulId = item.OkulId })">
                                        <img src="~/areas/CMS/assets/Images/edit_icon.png" style="width: 16px; height: 16px;" alt="Güncelle" />
                                    </a>
                                    <img src="/areas/CMS/assets/Images/delete_icon.png" onclick="konaklamaTipi.konaklamaTipiSil(@item.Id);" style="width: 16px; height: 16px;cursor:pointer;">
                                </td>
                            </tr>
                                    Counter++;
                        }
                    }
                    else
                    {
                        @*<tr><td colspan="3"><strong>Kayıt bulunamadı...</strong></td></tr>*@
                    }
                </tbody>
            </table>
        </td>
    </tr>

</table>

<script type="text/javascript">
    $(function () {

        konaklamaTipi.init();
        //konaklamaTipi.tarihGoster('konaklamaTipiOzelTarihGiris');
        //konaklamaTipi.tarihGoster('konaklamaTipiOzelTarihBitis');
        konaklamaTipi.tarihGosterRange('konaklamaTipiOzelTarihGiris', 'konaklamaTipiOzelTarihBitis');

    })

</script>

WebApp/Areas/cms/Views/KonaklamaFiyatlari/_KonaklamaMenu.cshtml
@{
    string pageUrl = Request.RawUrl.ToString();
    string okulId = Request.QueryString["okulId"];
}
<div class="fiyatTab">
    <a href="@Url.Action("KonaklamaTipi", "KonaklamaFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("KonaklamaTipi") ? "active" : "")">Konaklama Tipleri</a>
    <a href="@Url.Action("FiyatTanimlari", "KonaklamaFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("FiyatTanimlari") ? "active" : "")">Fiyat Tanımları</a>
    <a href="@Url.Action("PromosyonTanimlari", "KonaklamaFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("PromosyonTanimlari") ? "active" : "")">K. Promosyonları</a>   
    <a href="@Url.Action("KonaklamaEkUcretler", "KonaklamaFiyatlari", new { okulId = okulId })" class="@(pageUrl.Contains("KonaklamaEkUcretler") ? "active" : "")">Konaklama Ek Ücretler</a>   
</div>